-- 0. Desativar temporariamente a política dependente e apagar a função antiga
DROP POLICY IF EXISTS "users_volunteer_select_senior" ON public.users;
DROP FUNCTION IF EXISTS "private"."is_senior_on_visible_request"(target_user_id integer);

create extension if not exists "postgis" with schema "extensions";

create type "public"."metric_type" as enum ('HEART RATE', 'BLOOD OXYGEN', 'BLOOD PRESSURE', 'WEIGHT', 'TEMPERATURE', 'BLOOD GLUCOSE');

drop trigger if exists "on_private_request_insert" on "public"."requests";

drop trigger if exists "on_request_accepted" on "public"."requests";

drop trigger if exists "on_request_public_insert" on "public"."requests";

drop trigger if exists "on_request_public_update" on "public"."requests";

drop trigger if exists "on_notification_insert" on "public"."notifications";

drop policy "Allow anon select on monitoring" on "public"."monitoring";

drop policy "monitoring_caretaker_insert_senior" on "public"."monitoring";

drop policy "monitoring_caretaker_select_senior" on "public"."monitoring";

drop policy "monitoring_senior_insert_own" on "public"."monitoring";

drop policy "monitoring_senior_select_own" on "public"."monitoring";

drop policy "monitoring_senior_update_own" on "public"."monitoring";

drop policy "groceries_catalog_insert" on "public"."groceries";

drop function if exists "public"."notify_caretaker_on_senior_request"();

drop function if exists "public"."notify_volunteers_on_public_request"();


  create table "public"."metric_definitions" (
    "metric_type" public.metric_type not null,
    "unit" character varying(20) not null,
    "has_secondary" boolean not null default false,
    "secondary_label" character varying(50),
    "primary_label" character varying(50)
      );


alter table "public"."metric_definitions" enable row level security;

alter table "public"."monitoring" drop column "custom_metric_name";

alter table "public"."monitoring" drop column "custom_metric_value";

alter table "public"."monitoring" drop column "type";

alter table "public"."monitoring" drop column "value";

alter table "public"."monitoring" add column "created_at" timestamp with time zone not null default now();

alter table "public"."monitoring" add column "measured_at" timestamp with time zone not null;

alter table "public"."monitoring" add column "metric_type" public.metric_type not null;

alter table "public"."monitoring" add column "source" character varying(50) default 'health_connect'::character varying;

alter table "public"."monitoring" add column "value_primary" numeric(10,2) not null;

alter table "public"."monitoring" add column "value_secondary" numeric(10,2);

alter table "public"."monitoring" alter column "id" drop default;

alter table "public"."monitoring" alter column "id" add generated by default as identity;

alter table "public"."monitoring" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."monitoring" alter column "id_senior" set not null;

alter table "public"."monitoring" alter column "id_senior" set data type bigint using "id_senior"::bigint;

alter table "public"."notifications" add column "id_request" integer;

alter table "public"."notifications" alter column "expires_at" set default (now() + '05:00:00'::interval);

alter table "public"."users" add column "auth_provider" text;

alter table "public"."users" add column "location" extensions.geography(Point,4326);

alter table "public"."users" add column "onboarding_completed" boolean not null default false;

alter table "public"."users" alter column "password_hash" drop not null;

alter table "public"."vouchers" add column "location" extensions.geometry;

drop sequence if exists "public"."monitoring_id_seq";

CREATE INDEX idx_monitoring_measured_at ON public.monitoring USING btree (measured_at DESC);

CREATE INDEX idx_monitoring_senior_type ON public.monitoring USING btree (id_senior, metric_type);

CREATE UNIQUE INDEX metric_definitions_pkey ON public.metric_definitions USING btree (metric_type);

alter table "public"."metric_definitions" add constraint "metric_definitions_pkey" PRIMARY KEY using index "metric_definitions_pkey";

alter table "public"."monitoring" add constraint "chk_secondary_value" CHECK (((value_secondary IS NULL) OR (metric_type = 'BLOOD PRESSURE'::public.metric_type))) not valid;

alter table "public"."monitoring" validate constraint "chk_secondary_value";

alter table "public"."monitoring" add constraint "monitoring_metric_type_fkey" FOREIGN KEY (metric_type) REFERENCES public.metric_definitions(metric_type) not valid;

alter table "public"."monitoring" validate constraint "monitoring_metric_type_fkey";

alter table "public"."notifications" add constraint "notifications_id_request_fkey" FOREIGN KEY (id_request) REFERENCES public.requests(id) ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_id_request_fkey";

alter table "public"."users" add constraint "chk_password_required_for_email" CHECK ((((auth_provider = 'email'::text) AND (password_hash IS NOT NULL)) OR ((auth_provider <> 'email'::text) OR (auth_provider IS NULL)))) not valid;

alter table "public"."users" validate constraint "chk_password_required_for_email";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION private.is_senior_on_visible_request(senior_id integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_my_user_id integer;
  v_my_role user_role;
BEGIN
  -- Obter o ID do utilizador autenticado usando a função nativa da sua BD
  v_my_user_id := private.get_my_user_id();
  
  -- Se não estiver autenticado, não permitir
  IF v_my_user_id IS NULL THEN
    RETURN false;
  END IF;

  -- Obter a role do utilizador
  SELECT role INTO v_my_role FROM public.users WHERE id = v_my_user_id;

  -- Se for o próprio sénior a consultar os seus dados, permitir
  IF v_my_user_id = senior_id THEN
    RETURN true;
  END IF;

  -- Se for um voluntário, permitir ver se o sénior tem um pedido público pendente
  -- ou se o voluntário é o responsável pelo pedido
  IF v_my_role = 'VOLUNTEER'::user_role THEN
    RETURN EXISTS (
      SELECT 1 FROM public.requests r
      WHERE r.id_senior = senior_id
      AND (
        (r.state = 'PENDING'::req_state AND r.is_public = true)
        OR (r.state = 'ACCEPTED'::req_state AND r.id_volunteer = v_my_user_id)
      )
    );
  END IF;

  -- Se for um cuidador (Caretaker), permitir ver os seus séniores associados
  IF v_my_role = 'CARETAKER'::user_role THEN
    RETURN EXISTS (
      SELECT 1 FROM public.senior_caretaker sc
      WHERE sc.id_senior = senior_id
      AND sc.id_caretaker = v_my_user_id
    );
  END IF;

  RETURN false;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_user_id()
 RETURNS bigint
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT id FROM public.users WHERE auth_user_id = auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.on_request_change_create_notification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  senior_name TEXT;
  caretaker_id INT;
BEGIN
  -- Obter o nome do sénior dinamicamente
  SELECT name INTO senior_name FROM public.users WHERE id = NEW.id_senior;

  -- Obter o ID do cuidador associado ao sénior (se existir)
  SELECT id_caretaker INTO caretaker_id FROM public.senior_caretaker WHERE id_senior = NEW.id_senior LIMIT 1;

  -- ==========================================
  -- FLUXO DE INSERÇÃO (NOVO PEDIDO CRIADO)
  -- ==========================================
  IF TG_OP = 'INSERT' THEN
    IF NEW.is_public THEN
      -- A. Notificar o cuidador sobre o pedido feito à comunidade (community_request)
      IF caretaker_id IS NOT NULL THEN
        INSERT INTO public.notifications (type, description, id_senior, id_caretaker, id_request)
        VALUES (
          'community_request',
          senior_name || ' colocou um pedido de ' || COALESCE(NEW.category, 'ajuda') || ' na comunidade de voluntários.',
          NEW.id_senior,
          caretaker_id,
          NEW.id
        );
      END IF;

      -- B. Notificar a comunidade de voluntários (request público, mantendo o id_senior para a distância geográfica)
      INSERT INTO public.notifications (type, description, id_senior, id_request)
      VALUES (
        'request',
        'Novo pedido de ajuda disponível: ' || COALESCE(NEW.category, 'Pedido'),
        NEW.id_senior,
        NEW.id
      );
    ELSE
      -- Pedido direto ao cuidador:
      -- Tipo 'alert' para que envie notificação push privada ao cuidador e seja filtrado no sénior
      IF NEW.id_caretaker IS NOT NULL THEN
        INSERT INTO public.notifications (type, description, id_senior, id_caretaker, id_request)
        VALUES (
          'alert',
          senior_name || ' fez um novo pedido: ' || COALESCE(NEW.category, 'Pedido'),
          NEW.id_senior,
          NEW.id_caretaker,
          NEW.id
        );
      END IF;
    END IF;

  -- ==========================================
  -- FLUXO DE ATUALIZAÇÃO (MUDANÇA DE ESTADO)
  -- ==========================================
  ELSIF TG_OP = 'UPDATE' THEN
    IF NEW.state = 'ACCEPTED' AND OLD.state = 'PENDING' THEN
      INSERT INTO public.notifications (type, description, id_senior, id_volunteer, id_request)
      VALUES (
        'accepted_request',
        'O seu pedido foi aceite por um voluntário.',
        NEW.id_senior,
        NEW.id_volunteer,
        NEW.id
      );
    END IF;

    IF NEW.state = 'COMPLETED' AND OLD.state != 'COMPLETED' THEN
      INSERT INTO public.notifications (type, description, id_senior, id_volunteer, id_request)
      VALUES (
        'completed_request',
        'O seu pedido de ' || COALESCE(NEW.category, 'ajuda') || ' foi concluído. Clique para avaliar.',
        NEW.id_senior,
        NEW.id_volunteer,
        NEW.id
      );
    END IF;

    IF NEW.state = 'CANCELLED' AND OLD.state != 'CANCELLED' THEN
      INSERT INTO public.notifications (type, description, id_senior, id_volunteer, id_request)
      VALUES (
        'cancelled_request',
        'O seu pedido de ' || COALESCE(NEW.category, 'ajuda') || ' foi cancelado.',
        NEW.id_senior,
        NEW.id_volunteer,
        NEW.id
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION private.get_my_user_id()
 RETURNS integer
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT u.id
  FROM public.users u
  WHERE u.auth_user_id = auth.uid()
  LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION public.associate_with_code(p_code text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_creator_id integer;
    v_creator_role public.user_role;
    v_caller_id integer;
    v_caller_role public.user_role;
    v_senior_id integer;
    v_caretaker_id integer;
BEGIN
    v_caller_id := private.get_my_user_id();

    -- Buscar info do criador do codigo
    SELECT cc.id_user, u.role
    INTO v_creator_id, v_creator_role
    FROM public.connection_codes cc
    JOIN public.users u ON u.id = cc.id_user
    WHERE cc.code = p_code AND cc.expires_at > now();

    IF v_creator_id IS NULL THEN
        RAISE EXCEPTION 'Codigo invalido ou expirado.';
    END IF;

    IF v_creator_id = v_caller_id THEN
        RAISE EXCEPTION 'Nao podes usar o teu proprio codigo.';
    END IF;

    -- Buscar role de quem esta a executar
    SELECT role INTO v_caller_role FROM public.users WHERE id = v_caller_id;

    -- Determinar quem e quem
    IF v_creator_role = 'SENIOR' AND v_caller_role = 'CARETAKER' THEN
        v_senior_id := v_creator_id;
        v_caretaker_id := v_caller_id;
    ELSIF v_creator_role = 'CARETAKER' AND v_caller_role = 'SENIOR' THEN
        v_senior_id := v_caller_id;
        v_caretaker_id := v_creator_id;
    ELSE
        RAISE EXCEPTION 'A associacao deve ser entre um Cuidador e um Senior.';
    END IF;

    -- Inserir na tabela (se ja existir vai ignorar ou dar erro, por isso testamos)
    IF NOT EXISTS (SELECT 1 FROM public.senior_caretaker WHERE id_senior = v_senior_id AND id_caretaker = v_caretaker_id) THEN
        INSERT INTO public.senior_caretaker (id_senior, id_caretaker) VALUES (v_senior_id, v_caretaker_id);
    END IF;

    -- Apagar o codigo para que nao seja reutilizado
    DELETE FROM public.connection_codes WHERE code = p_code;

    RETURN true;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.check_medications()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.notifications (type, description, id_senior)
  SELECT 
    'medication',
    'Está na hora de tomar: ' || name,
    id_senior
  FROM public.medicine
  WHERE status = 'TO TAKE'
    -- Extrair a hora e minuto do scheduled_time e comparar com a hora e minuto atual
    AND to_char(scheduled_time, 'HH24:MI') = to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Lisbon', 'HH24:MI')
    -- E estar dentro da data de tratamento
    AND (start_date IS NULL OR start_date::date <= CURRENT_DATE)
    AND (end_date IS NULL OR end_date::date >= CURRENT_DATE);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_voucher_tasks_on_request_complete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Só atuar quando o estado muda para COMPLETED
  IF NEW.state = 'COMPLETED' AND (OLD.state IS DISTINCT FROM 'COMPLETED') THEN
    -- Verificar se há um voluntário associado ao pedido
    IF NEW.id_volunteer IS NOT NULL THEN
      -- Incrementar current_tasks em todos os vouchers do voluntário que não estejam USED
      UPDATE public.vouchers_volunteer
      SET current_tasks = current_tasks + 1
      WHERE id_volunteer = NEW.id_volunteer
        AND status != 'USED';
    END IF;
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_caretaker_on_abnormal_sensor()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  sensor_record RECORD;
  is_abnormal BOOLEAN := FALSE;
  current_hour INTEGER;
BEGIN
  -- Extrair a hora atual
  current_hour := EXTRACT(HOUR FROM CURRENT_TIMESTAMP);

  -- Regras de anomalia (exemplo)
  IF NEW.type = 'motion' AND (current_hour >= 0 AND current_hour <= 5) THEN
    -- Movimento detetado de madrugada (entre meia-noite e 5h)
    is_abnormal := TRUE;
  ELSIF NEW.value ILIKE '%alarm%' OR NEW.value ILIKE '%danger%' THEN
    -- String explicita de alarme
    is_abnormal := TRUE;
  END IF;

  IF is_abnormal THEN
    -- Obter os dados do sensor para saber quem avisar
    SELECT id_caretaker, id_senior INTO sensor_record 
    FROM public.sensors 
    WHERE id = NEW.id_sensor;

    IF FOUND AND sensor_record.id_caretaker IS NOT NULL THEN
      INSERT INTO public.notifications (type, description, id_caretaker, id_senior)
      VALUES (
        'alert',
        'Alerta de Sensor: Atividade invulgar detetada (' || NEW.type || ')',
        sensor_record.id_caretaker,
        sensor_record.id_senior
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_senior_on_request_accepted()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  accepter_name text;
BEGIN
  -- Se o estado mudou para ACCEPTED
  IF NEW.state = 'ACCEPTED' AND OLD.state != 'ACCEPTED' THEN
    
    -- Tentar obter o nome de quem aceitou (Voluntário ou Cuidador)
    -- Num pedido público, quem aceita é o id_volunteer
    IF NEW.id_volunteer IS NOT NULL THEN
      SELECT name INTO accepter_name FROM public.users WHERE id = NEW.id_volunteer;
    -- Se não for público, quem aceita é o id_caretaker
    ELSIF NEW.id_caretaker IS NOT NULL THEN
      SELECT name INTO accepter_name FROM public.users WHERE id = NEW.id_caretaker;
    END IF;

    -- Inserir notificação destinada ao Sénior
    INSERT INTO public.notifications (type, description, id_senior)
    VALUES (
      'accepted_request',
      'O teu pedido de ' || COALESCE(NEW.category, 'ajuda') || ' foi aceite por ' || COALESCE(accepter_name, 'um voluntário') || '!',
      NEW.id_senior
    );
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.send_expo_push_notification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  user_push_token text;
  payload jsonb;
BEGIN
  -- Tentar obter token do cuidador (alertas e pedidos)
  IF NEW.id_caretaker IS NOT NULL THEN
    SELECT push_token INTO user_push_token FROM public.users WHERE id = NEW.id_caretaker;
  END IF;

  -- Tentar obter token do sénior (ex: lembretes de medicação)
  IF user_push_token IS NULL AND NEW.id_senior IS NOT NULL THEN
    SELECT push_token INTO user_push_token FROM public.users WHERE id = NEW.id_senior;
  END IF;

  -- Tentar obter token do voluntário
  IF user_push_token IS NULL AND NEW.id_volunteer IS NOT NULL THEN
    SELECT push_token INTO user_push_token FROM public.users WHERE id = NEW.id_volunteer;
  END IF;

  IF user_push_token IS NOT NULL THEN
    payload := json_build_object(
      'to',    user_push_token,
      'sound', 'default',
      'title', CASE 
                 WHEN NEW.type = 'medication' THEN '💊 Lembrete de Medicação'
                 WHEN NEW.type = 'alert' THEN '🚨 Alerta de Segurança'
                 WHEN NEW.type = 'request' THEN '🔔 Novo Pedido'
                 ELSE '🔔 Geras'
               END,
      'body',  NEW.description
    )::jsonb;

    PERFORM net.http_post(
      url     := 'https://exp.host/--/api/v2/push/send'::text,
      body    := payload,
      headers := '{"Content-Type": "application/json"}'::jsonb
    );
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.send_push_to_all_volunteers()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  vol RECORD;
  payload text;
BEGIN
  -- Iterar sobre todos os voluntários com push_token registado
  FOR vol IN
    SELECT id, push_token
    FROM public.users
    WHERE role = 'VOLUNTEER'
      AND push_token IS NOT NULL
      AND push_token <> ''
  LOOP
    payload := json_build_object(
      'to',    vol.push_token,
      'sound', 'default',
      'title', '🤝 Novo Pedido de Ajuda',
      'body',  COALESCE(NEW.description, 'Há um pedido de ajuda na tua área!')
    )::text;

    PERFORM net.http_post(
      url      := 'https://exp.host/--/api/v2/push/send'::text,
      body     := payload::jsonb,
      headers  := '{"Content-Type": "application/json", "Accept": "application/json"}'::jsonb
    );
  END LOOP;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_user_auth_id()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  -- Faz o INSERT. O raw_user_meta_data é enviado do Frontend no signUp.
  insert into public.users (
    auth_user_id, 
    email, 
    password_hash, 
    name, 
    role
  )
  values (
    new.id,
    new.email,
    'handled_by_supabase_auth', -- Campo obrigatório na DB, mas inutilizado
    coalesce(new.raw_user_meta_data->>'name', 'Sem Nome'),
    cast(coalesce(new.raw_user_meta_data->>'role', 'SENIOR') as public.user_role)
  )
  on conflict (email) do update
  set auth_user_id = excluded.auth_user_id,
      name = excluded.name,
      role = excluded.role;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_voucher_status()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  required_tasks integer;
BEGIN
  -- Não mexer em vouchers já utilizados (cast para text para garantir comparação correta)
  IF NEW.status::text = 'USED' THEN
    RETURN NEW;
  END IF;

  -- Buscar o número de tarefas necessárias
  SELECT needed_tasks INTO required_tasks
  FROM public.vouchers
  WHERE id = NEW.id_voucher;

  -- Atualizar o status com base no progresso
  IF NEW.current_tasks >= required_tasks THEN
    NEW.status := 'AVAILABLE';
  ELSE
    NEW.status := 'UNAVAILABLE';
  END IF;

  RETURN NEW;
END;
$function$
;

grant delete on table "public"."metric_definitions" to "anon";

grant insert on table "public"."metric_definitions" to "anon";

grant references on table "public"."metric_definitions" to "anon";

grant select on table "public"."metric_definitions" to "anon";

grant trigger on table "public"."metric_definitions" to "anon";

grant truncate on table "public"."metric_definitions" to "anon";

grant update on table "public"."metric_definitions" to "anon";

grant delete on table "public"."metric_definitions" to "authenticated";

grant insert on table "public"."metric_definitions" to "authenticated";

grant references on table "public"."metric_definitions" to "authenticated";

grant select on table "public"."metric_definitions" to "authenticated";

grant trigger on table "public"."metric_definitions" to "authenticated";

grant truncate on table "public"."metric_definitions" to "authenticated";

grant update on table "public"."metric_definitions" to "authenticated";

grant delete on table "public"."metric_definitions" to "service_role";

grant insert on table "public"."metric_definitions" to "service_role";

grant references on table "public"."metric_definitions" to "service_role";

grant select on table "public"."metric_definitions" to "service_role";

grant trigger on table "public"."metric_definitions" to "service_role";

grant truncate on table "public"."metric_definitions" to "service_role";

grant update on table "public"."metric_definitions" to "service_role";


  create policy "metric_definitions_select_policy"
  on "public"."metric_definitions"
  as permissive
  for select
  to authenticated
using (true);



  create policy "monitoring_delete_policy_caretaker"
  on "public"."monitoring"
  as permissive
  for delete
  to authenticated
using ((auth.uid() IN ( SELECT u.auth_user_id
   FROM (public.users u
     JOIN public.senior_caretaker sc ON ((sc.id_caretaker = u.id)))
  WHERE (sc.id_senior = monitoring.id_senior))));



  create policy "monitoring_delete_policy_senior"
  on "public"."monitoring"
  as permissive
  for delete
  to authenticated
using ((auth.uid() IN ( SELECT users.auth_user_id
   FROM public.users
  WHERE (users.id = monitoring.id_senior))));



  create policy "monitoring_insert_policy"
  on "public"."monitoring"
  as permissive
  for insert
  to authenticated
with check (((id_senior = public.get_my_user_id()) OR (EXISTS ( SELECT 1
   FROM public.senior_caretaker
  WHERE ((senior_caretaker.id_senior = monitoring.id_senior) AND (senior_caretaker.id_caretaker = public.get_my_user_id()))))));



  create policy "monitoring_select_policy"
  on "public"."monitoring"
  as permissive
  for select
  to authenticated
using (((id_senior = public.get_my_user_id()) OR (EXISTS ( SELECT 1
   FROM public.senior_caretaker
  WHERE ((senior_caretaker.id_senior = monitoring.id_senior) AND (senior_caretaker.id_caretaker = public.get_my_user_id()))))));



  create policy "monitoring_update_policy_caretaker"
  on "public"."monitoring"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.senior_caretaker
  WHERE ((senior_caretaker.id_senior = monitoring.id_senior) AND (senior_caretaker.id_caretaker = ( SELECT users.id
           FROM public.users
          WHERE (users.auth_user_id = auth.uid())))))))
with check ((EXISTS ( SELECT 1
   FROM public.senior_caretaker
  WHERE ((senior_caretaker.id_senior = monitoring.id_senior) AND (senior_caretaker.id_caretaker = ( SELECT users.id
           FROM public.users
          WHERE (users.auth_user_id = auth.uid())))))));



  create policy "monitoring_update_policy_senior"
  on "public"."monitoring"
  as permissive
  for update
  to authenticated
using ((id_senior = ( SELECT users.id
   FROM public.users
  WHERE (users.auth_user_id = auth.uid()))))
with check ((id_senior = ( SELECT users.id
   FROM public.users
  WHERE (users.auth_user_id = auth.uid()))));



  create policy "Permitir inserção do próprio perfil"
  on "public"."users"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = auth_user_id));



  create policy "users_select_own"
  on "public"."users"
  as permissive
  for select
  to authenticated
using ((id = private.get_my_user_id()));



  create policy "vouchers_volunteer_insert_policy_volunteer"
  on "public"."vouchers_volunteer"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = ( SELECT u.auth_user_id
   FROM public.users u
  WHERE (u.id = vouchers_volunteer.id_volunteer))));



  create policy "groceries_catalog_insert"
  on "public"."groceries"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) IS NOT NULL));


CREATE TRIGGER trigger_on_request_change AFTER INSERT OR UPDATE ON public.requests FOR EACH ROW EXECUTE FUNCTION public.on_request_change_create_notification();

CREATE TRIGGER on_notification_insert AFTER INSERT ON public.notifications FOR EACH ROW WHEN (((new.type)::text = ANY (ARRAY['alert'::text, 'medication'::text]))) EXECUTE FUNCTION public.send_expo_push_notification();


-- Recriar a política que depende da função atualizada
CREATE POLICY "users_volunteer_select_senior"
ON public.users FOR SELECT TO authenticated
USING (
  private.is_senior_on_visible_request(public.users.id)
);
